"""Public contracts and ports for the governed analytics agent."""

from typing import TYPE_CHECKING, Any

from governed_analytics.agent.contracts import (
    ActionType,
    AgentAction,
    AgentFinishReason,
    AgentRunResult,
    AnalysisAction,
    AnalysisType,
    AnswerContract,
    BehaviorAction,
    BehaviorDecision,
    BehaviorReasonCode,
    ColumnContract,
    ContextBundle,
    EvidenceAssessment,
    EvidenceItem,
    FinalAnswer,
    FinalStatus,
    FrozenJsonObject,
    GovernanceSnapshot,
    Hypothesis,
    JsonScalar,
    JsonValue,
    ModelCallTrace,
    ModelPurpose,
    ModelReservation,
    ModelUsage,
    NodeTrace,
    Observation,
    ObservationContract,
    ObservationValidation,
    RepairDecision,
    RepairRecord,
    ResultShape,
    RunLifecycleStatus,
    SafeTrace,
    SortKey,
    StopReason,
    StructuredInvocation,
    StructuredModelRequest,
    StructuredModelResult,
    TimeWindow,
    ToolCallTrace,
    ToolInvocation,
    TypedMetricPlan,
)
from governed_analytics.agent.ports import (
    AgentContext,
    AgentModel,
    AgentTools,
    BudgetPort,
    Clock,
    EventSink,
    ModelInvoker,
    StructuredInvocationError,
    TraceRecorder,
)
from governed_analytics.agent.state import AgentState, new_agent_state
from governed_analytics.agent.tracing import InMemoryTraceRecorder

if TYPE_CHECKING:
    from governed_analytics.agent.graph import build_agent_graph, run_agent


def __getattr__(name: str) -> Any:
    if name in {"build_agent_graph", "run_agent"}:
        from governed_analytics.agent import graph

        return getattr(graph, name)
    raise AttributeError(name)


__all__ = [
    "ActionType",
    "AgentAction",
    "AgentContext",
    "AgentFinishReason",
    "AgentModel",
    "AgentRunResult",
    "AgentState",
    "AgentTools",
    "AnalysisAction",
    "AnalysisType",
    "AnswerContract",
    "BehaviorAction",
    "BehaviorDecision",
    "BehaviorReasonCode",
    "BudgetPort",
    "Clock",
    "ColumnContract",
    "ContextBundle",
    "EventSink",
    "EvidenceAssessment",
    "EvidenceItem",
    "FinalAnswer",
    "FinalStatus",
    "FrozenJsonObject",
    "GovernanceSnapshot",
    "Hypothesis",
    "InMemoryTraceRecorder",
    "JsonScalar",
    "JsonValue",
    "ModelCallTrace",
    "ModelInvoker",
    "ModelPurpose",
    "ModelReservation",
    "ModelUsage",
    "NodeTrace",
    "Observation",
    "ObservationContract",
    "ObservationValidation",
    "RepairDecision",
    "RepairRecord",
    "ResultShape",
    "RunLifecycleStatus",
    "SafeTrace",
    "SortKey",
    "StopReason",
    "StructuredInvocation",
    "StructuredInvocationError",
    "StructuredModelRequest",
    "StructuredModelResult",
    "TimeWindow",
    "ToolCallTrace",
    "ToolInvocation",
    "TraceRecorder",
    "TypedMetricPlan",
    "build_agent_graph",
    "new_agent_state",
    "run_agent",
]
